"""Spotfire expression normalizer for DuckDB SQL."""

from .catalog import catalog_db_path, unsupported_functions_markdown_path
from .compiler import ExpressionIrPrepareResult, compile_expressions_to_ir, prepare_expression_ir
from .ir import IR_VERSION, ExpressionIrDocument, IrExpression
from .normalizer import (
    SUPPORTED_SPOTFIRE_FUNCTIONS,
    DerivedExpression,
    DuckDbLayeredExpressionPrepareResult,
    ExpressionCompatibilityError,
    ExpressionCompileResult,
    PolarsExpression,
    PolarsExpressionCompileResult,
    PolarsLayeredExpressionPrepareResult,
    build_expression_layers,
    build_raw_expressions,
    canonicalize_expressions,
    compile_expression_file,
    compile_polars_expression_file,
    extract_identifier_tokens,
    load_duckdb_layered_expression_yaml,
    load_expression_items_from_csv,
    load_expression_items_from_yaml,
    load_polars_layered_expression_yaml,
    normalize_expression,
    normalize_expression_for_polars,
    normalize_spotfire_expression_for_duckdb,
    normalize_spotfire_expression_for_polars,
    prepare_duckdb_layered_expression,
    prepare_polars_layered_expression,
    pretty_format_expression,
    validate_expression_compatibility,
    write_duckdb_layered_expression_yaml,
    write_layered_expression_yaml,
    write_polars_layered_expression_yaml,
    write_unsupported_expression_yaml,
)
from .parser import parse_expression
from .rust_support import (
    RUST_COMPILER_ONLY_ALIASES,
    RUST_EXPLICIT_UNSUPPORTED,
    RustFunctionCoverage,
    rust_function_coverage,
    validate_rust_ir_function_support,
)
from .semantics import FunctionSemantics, canonical_function_semantics
from .tokenizer import tokenize_expression

__all__ = [
    "IR_VERSION",
    "RUST_COMPILER_ONLY_ALIASES",
    "RUST_EXPLICIT_UNSUPPORTED",
    "SUPPORTED_SPOTFIRE_FUNCTIONS",
    "DerivedExpression",
    "DuckDbLayeredExpressionPrepareResult",
    "ExpressionCompatibilityError",
    "ExpressionCompileResult",
    "ExpressionIrDocument",
    "ExpressionIrPrepareResult",
    "FunctionSemantics",
    "IrExpression",
    "PolarsExpression",
    "PolarsExpressionCompileResult",
    "PolarsLayeredExpressionPrepareResult",
    "RustFunctionCoverage",
    "build_expression_layers",
    "build_raw_expressions",
    "canonical_function_semantics",
    "canonicalize_expressions",
    "catalog_db_path",
    "compile_expression_file",
    "compile_expressions_to_ir",
    "compile_polars_expression_file",
    "extract_identifier_tokens",
    "load_duckdb_layered_expression_yaml",
    "load_expression_items_from_csv",
    "load_expression_items_from_yaml",
    "load_polars_layered_expression_yaml",
    "normalize_expression",
    "normalize_expression_for_polars",
    "normalize_spotfire_expression_for_duckdb",
    "normalize_spotfire_expression_for_polars",
    "parse_expression",
    "prepare_duckdb_layered_expression",
    "prepare_expression_ir",
    "prepare_polars_layered_expression",
    "pretty_format_expression",
    "rust_function_coverage",
    "tokenize_expression",
    "unsupported_functions_markdown_path",
    "validate_expression_compatibility",
    "validate_rust_ir_function_support",
    "write_duckdb_layered_expression_yaml",
    "write_layered_expression_yaml",
    "write_polars_layered_expression_yaml",
    "write_unsupported_expression_yaml",
]
